### ISSUE TITLE
InventoryDragEvent isn't caught in custom inventories

### ISSUE THREAD

**Issue by Phoenix616** [DrOreo002/OreoCore#1]
As far as I can tell you are only listening for the InventoryClickEvent for CustomInventory interaction. This allows moving of items into the inventory (or maybe even out if done right, at least it might lead to clicks not registering when slightly moving the mouse when clicking)

**Comment by DrOreo002** [comment]
Hey, sorry for the late response xD, I'll look into that now. Thanks for reporting!
