### ISSUE TITLE
Large lag spikes occasionally with this plugin

### ISSUE THREAD

**Issue by TerdyTheTerd** [DrOreo002/OreoCore#2]
Been having occasional large lag spikes when players join on my server. Finally ran some timings reports and OreoCore onPlayerJoinEvent takes 5 seconds everytime someone joins, perhaps a timeout value for something?
![image](https://user-images.githubusercontent.com/9743432/108017289-23da6100-6fda-11eb-9961-72e03bd0e63b.png)

**Comment by DrOreo002** [comment]
Hey, I know this is a really late response (forgot to watch this repo lol) but currently the plugin is abandoned. The code is really old and I wrote it when I was like 2 years into programming so its poorly optimized, I'd suggest to not force your server running this plugin.

Closing this and archived the repo
